#!/usr/bin/env bash
# This script installs and configures nginx to serve "Holberton School"

sudo apt-get update
sudo apt-get -y install nginx

echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null

sudo service nginx restart
